### ISSUE TITLE
Samples ID: ctb0064-9294 (1976); ctb0064-9305(1977); ctb0064-9333 (1978); (River)

### ISSUE THREAD

**Issue by CardosoMvs** [Laboratorio-de-Pedometria/mapbiomas-soc#10]
![image](https://github.com/Laboratorio-de-Pedometria/mapbiomas-soc/assets/127773820/c2352b4d-d434-4808-8410-9f8458baee11)

The three samples are in the same location, in water, in subsequent years.

**Sample ID: ctb0064-9294**
**Collection Year**: 1976

**Sample ID: ctb0064-9305**
**Collection Year**: 1977

**Sample ID: ctb0064-9333**
**Collection Year**: 1978

**Location**: Macapá
**Coordinates**:
Latitude: 0.8323670163435818
Longitude: -50.28092603797995
**Masked Attributes**:
 Geomorphometry e  granulometry mapbiomas

**Comment by samuel-rosa** [comment]
Os dados do `ctb0064` são provenientes do PronaSolos. Nós identificamos problemas sérios nesses dados em #1 . Por isso, decidimos não mais utilizar esses dados, que serão descartados.
