### ISSUE TITLE
Sample ID: ctb0064-8058 (Coastal Coast) 

### ISSUE THREAD

**Issue by CardosoMvs** [Laboratorio-de-Pedometria/mapbiomas-soc#14]
![image](https://github.com/Laboratorio-de-Pedometria/mapbiomas-soc/assets/127773820/32c0b26e-c84c-46d3-b381-dc077e497acb)

The sample location is in the water, on the coastal coast, in Salvador

**Collection Year**: 1973
**Location**: Salvador
**Coordinates**:
Latitude: -12.890347029796077
Longitude: -38.65954552687245
**Masked Attributes**:
Geomorphometry, Granulometry e FCN

**Comment by samuel-rosa** [comment]
Os dados do `ctb0064` são proveninentes do PronaSolos. Nós identificamos problemas importantes nesses dados em #1 e, por isso, decidimos que esses dados não serão mais utilizados em nosso trabalho.
